@startuml
title WarmHouse Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "A user of the SmartHouse system")
System(SmartHouseSystem, "Smart House System", "System managing, register and telemetry devices")

System_Ext(HeatingSystem, "Heating System", "External Heating System for managing")

Rel(user, SmartHouseSystem, "Uses the system")
Rel(SmartHouseSystem, HeatingSystem, "Manage and register devices")

@enduml